CREATE TABLE SS_PERSON
(
  USER_ID       NUMBER(10)         NOT NULL,
  LOGIN         VARCHAR2(255 BYTE) NOT NULL,
  FIRST_NAME    VARCHAR2(255 BYTE)         ,
  LAST_NAME     VARCHAR2(255 BYTE)         ,
  EMAIL         VARCHAR2(255 BYTE)         ,
  PASSWORD_HASH VARCHAR2(40),
  CONSTRAINT PERSON_PK PRIMARY KEY (USER_ID),
  CONSTRAINT PERSON_UQ UNIQUE (LOGIN)
)
/